## Simulation Exercises

In [21]:
# importing data
import numpy as np
import pandas as pd



#### How likely is it that you roll doubles when rolling two dice?

In [9]:
# establish base dice and trials
ndice = ncols = 2
ntrials = nrows = 10**6

# create simulated rolls, use product of rows and cols as size
# reshape to fit the needs of the simulation
rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows*ncols).reshape(nrows, ncols)
rolls

array([[3, 4],
       [6, 1],
       [4, 1],
       ...,
       [6, 3],
       [6, 1],
       [4, 5]])

In [10]:
# Success is when both values in the row equal the same
# creating boolean for when the values of column 0 are equal to the value of col 1
success_rate = (rolls[:,0] == rolls[:,1])


success_rate.mean()

0.166841

#### If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [18]:
# establish the columns as the coiuns
ncoins = ncols = 8
# create a large number of trials as rows (each row = 1 round of flips)
ntrials = nrows = 10**5

# Create the simulated results with choices being heads or tails
# the number of selected choices is the ncols times nrows
# reshaping the choices to have the rows we want and the columns we want
flips = np.random.choice(['heads', 'tails'], ncols * nrows).reshape(nrows, ncols)
flips

array([['tails', 'heads', 'tails', ..., 'heads', 'tails', 'heads'],
       ['tails', 'tails', 'tails', ..., 'heads', 'tails', 'heads'],
       ['tails', 'tails', 'heads', ..., 'tails', 'tails', 'tails'],
       ...,
       ['heads', 'tails', 'heads', ..., 'tails', 'heads', 'heads'],
       ['heads', 'tails', 'tails', ..., 'heads', 'heads', 'heads'],
       ['tails', 'tails', 'heads', ..., 'heads', 'heads', 'tails']],
      dtype='<U5')

In [19]:
# success is getting exactly 3 heads, now lets find the probablility
# first, get true false values for the success metric
is_heads = flips == 'heads'
is_heads

array([[False,  True, False, ...,  True, False,  True],
       [False, False, False, ...,  True, False,  True],
       [False, False,  True, ..., False, False, False],
       ...,
       [ True, False,  True, ..., False,  True,  True],
       [ True, False, False, ...,  True,  True,  True],
       [False, False,  True, ...,  True,  True, False]])

In [20]:
# now sum the the boolean values and if the boolean value is equal to three then it is success
success_rates = (is_heads.sum(axis=1) == 3)
success_rates

# finally, we will take the average of all the trials to find the probablility of getting exactly three heads
success_rates.mean()

0.21936

In [22]:
# sum the boolean values and if there are more than 3 heads, then that is success
success_rates = is_heads.sum(axis = 1) > 3
success_rates

# caluculate the mean of the boolean values to get the probablilty of more than 3 heads
success_rates.mean()

0.63694

#### There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [25]:
# Setup up the simulation
# there are two billboard that are being driven by
nbillb = ncols = 2
# we want many trials
ntrials = nrows = 10**5

# for this, inside the random choice the ratio of wb dev student to data science students can be realized
cohorts = np.random.choice(['web', 'web', 'web', 'data'], ncols * nrows).reshape(nrows, ncols)
cohorts

# or
np.random.choice(['web', 'data'], size=(nrows, ncols), p = [0.75, 0.25])

array([['web', 'web'],
       ['web', 'web'],
       ['web', 'web'],
       ...,
       ['data', 'web'],
       ['web', 'web'],
       ['web', 'web']], dtype='<U4')

In [71]:
# we want the probablity of successfully seeing 2 data science studetns on the billboards
# first, we will create a variable holding the boolena values for if there is a ds student ont he billboard
is_data = cohorts == 'data'
is_data

# now we will sum up the booleanb values, we want 2 successes
success = (is_data.sum(axis=1) == 2)
success

# now we will take the average of this variable to find the probability of seeing ds studetns on both billboards
success.mean()

0.0617

#### Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [20]:
# setup
# the columns are the days of class (4 for M - Th - Fridsay not included because we are purchasing on friday )
ndays = ncols = 5
# the trials are differnt simualtions of the 5 days in a weeks
ntrials = nrows = 10**4
# now establish the restock amount
restock = 17
# this will give us the amount of poptarts eaten on a based on the information provided in the prompt
eaten = np.random.normal(3, 1.5, nrows * ncols).reshape(nrows, ncols)
eaten

array([[5.40901158, 2.2751747 , 1.90409839, 2.46746022, 2.85479083],
       [2.18691709, 4.08533024, 2.8707127 , 0.55665326, 6.40859019],
       [2.97377868, 4.18046422, 3.37803255, 2.47833624, 3.96824088],
       ...,
       [1.58620766, 3.45318222, 4.11732314, 3.15729421, 0.15683056],
       [2.64939742, 3.39676139, 4.84639308, 3.92271138, 5.54583762],
       [2.63256014, 1.27069318, 4.39140829, 3.05667641, 4.13182113]])

In [25]:
eaten[eaten < 0] = 0
# Success is having poptarts friday afternoon, first we will calucalate weekly poptart consumptiom
weekly_consumption = eaten.sum(axis=1)
weekly_consumption

# Lets find the likelihood there are leftovers after each week
# if the difference between the retock and the weekly consumption is 1 or more, that is success
leftovers = (restock - weekly_consumption) >= 1

leftovers.mean()

# 

(weekly_consumption < restock).mean()

0.7185

#### Compare Heights
>Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [36]:
# two columns, one is mens height, the other is womens height
nrows = 10**5

# get simulated heights randomly generated based on the provided information
man = np.random.normal(178, 8, nrows)
woman = np.random.normal(170, 6, nrows)

# now put these into a matrix that we can use, transposing it so the information if how we woul like it to be
heights = np.matrix([man, woman]).T

In [48]:
# success in this instance is a woman being taller than a man
is_she_taller = (heights[:,1] - heights[:,0]) > 0

# now take the mean of the results to get the probalilty
is_she_taller.mean()

0.2136

#### When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [57]:
# creating the rows and columns
downloads = ncols = 500
ntrials = nrows = 10 ** 5

# Creating the probability of corruption in a list
chances = list('S' * 249)
chances.append('C')
chances

# creating the np array of the downloads
installations = np.random.choice(['i', 'c'], size = (nrows, ncols), p = [(249/250), (1/250)])
# np.random.choice(chances, ncols * nrows).reshape(nrows, ncols)
installations

array([['i', 'i', 'i', ..., 'i', 'i', 'i'],
       ['i', 'i', 'i', ..., 'i', 'i', 'i'],
       ['i', 'i', 'i', ..., 'i', 'i', 'i'],
       ...,
       ['i', 'i', 'i', ..., 'i', 'i', 'i'],
       ['i', 'i', 'i', ..., 'i', 'i', 'i'],
       ['i', 'i', 'i', ..., 'i', 'i', 'i']], dtype='<U1')

In [58]:
# first, what is the chance of success that 50 students are successful ith installation?
# create boolean values for each install in the data
first_fifty_succeed = (installations[:,:50] == 'i')

# sum the boolean values for assigned in the variable along axis 1, if == 50 then they successfuly installed, if not there is a corruptio
success = (first_fifty_succeed.sum(axis=1) == 50)

# Take the mean of the new boolean values to find the lilelihood that it was correct
success.mean()

0.81996

In [59]:
# next is for 100
hundred_installs = installations[:,:100] == 'i'
hundred_installs.shape

# sum them all, if the sum across the x axis equals 100, then success
success = hundred_installs.sum(axis=1) == 100

# take the mean for the likelihood
success.mean()

0.67197

>What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [60]:
# now the likelihood that there IS an issue in 150
onefifty_issue = installations[:, :150] == 'c'
onefifty_issue.shape

# Sum, if there is one 'C', one true, or a sum of at least one then that is success
success = onefifty_issue.sum(axis=1) >= 1

success.mean()

0.44905

>How likely is it that 450 students all download anaconda without an issue?

In [55]:
# likelihood of 450 no issues
fourfifty_installs = installations[:, :450] == 'i'
fourfifty_installs.shape

# if the sum of all the values is equal to 450 then that is success
success = fourfifty_installs.sum(axis=1) == 450

# mean for the probabilty
success.mean()

0.16534

#### There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [65]:
#Setup
# set up the days as columns
days = ncols = 3
# set up the trials
ntrials = nrows = 10**5

# create the simualted data using 
travis_food = np.random.choice(['f', 'f', 'f', 'f', 'f', 'f', 'f', 'n','n','n'], nrows*ncols).reshape(nrows, ncols)
travis_food

array([['f', 'f', 'f'],
       ['f', 'f', 'n'],
       ['f', 'f', 'f'],
       ...,
       ['f', 'f', 'f'],
       ['n', 'f', 'f'],
       ['f', 'n', 'n']], dtype='<U1')

In [66]:
# success is no food trucks or all 'n'
no_food = travis_food == 'n'

# sum all the numbers, if they are equal to 3 then that is success
success = no_food.sum(axis=1) == 3

success.mean()

0.02645

>How likely is it that a food truck will show up sometime this week?

In [67]:
# Setup for 7 days
# set up the days as columns
days = ncols = 7
# set up the trials
ntrials = nrows = 10**5

# create the simualted data using 
travis_food = np.random.choice(['f', 'f', 'f', 'f', 'f', 'f', 'f', 'n','n','n'], nrows*ncols).reshape(nrows, ncols)
travis_food.shape

(100000, 7)

In [68]:
# Putting all the steps t0gether here 
food_this_week = (travis_food == 'f').sum(axis=1) >= 1

food_this_week.mean()

0.99983

#### If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [2]:
# establish the columns, the number of 
npeople = ncols = 23
# establish trials
ntrials = nrows = 10**5

# there are 365 days in a year, with one day being a birthday, creating this
chances = list('d' * 364)
chances.append('B')
chances

# now to create the simualted data
birthdays_in_room = np.random.choice(chances, nrows * ncols).reshape(nrows, ncols)
birthdays_in_room.shape

# create boolean with true for birthdays
two_birthdays = (birthdays_in_room == 'B').sum(axis=1) == 2

two_birthdays.mean()

0.00193

In [107]:
birthdays = np.random.choice(['d', 'B'], size = (nrows, ncols), p = [364/365, 1/365])

at_least_two = ((birthdays_in_room == 'B').sum(axis=1) > 1)
at_least_two.mean()

0.00195

In [4]:
chances = list(range(1, 366))
chances
birthdays = np.random.choice(chances, size = (nrows, ncols))

In [6]:
birthdays_df = pd.DataFrame(birthdays)

In [27]:
(birthdays_df.nunique(axis=1) == 22).mean()

0.36404

In [80]:
## 20 people
# establish the columns, the number of 
npeople = ncols = 20
# establish trials
ntrials = nrows = 10**5

# there are 365 days in a year, with one day being a birthday, creating this
chances = list('d' * 364)
chances.append('B')
chances

# now to create the simualted data
birthdays_in_room = np.random.choice(chances, nrows * ncols).reshape(nrows, ncols)
birthdays_in_room.shape

# create boolean with true for birthdays
two_birthdays = (birthdays_in_room == 'B').sum(axis=1) == 2

two_birthdays.mean()


0.00126

In [81]:
## 40 people 
# establish the columns, the number of 
npeople = ncols = 40
# establish trials
ntrials = nrows = 10**5

# there are 365 days in a year, with one day being a birthday, creating this
chances = list('d' * 364)
chances.append('B')
chances

# now to create the simualted data
birthdays_in_room = np.random.choice(chances, nrows * ncols).reshape(nrows, ncols)
birthdays_in_room.shape

# create boolean with true for birthdays
two_birthdays = (birthdays_in_room == 'B').sum(axis=1) == 2

two_birthdays.mean()

0.00553